import Link from "next/link";
import {
  MapPinned,
  Layers,
  Building2,
  TrendingUp,
  Check,
  Sparkles,
  MapPin,
  Repeat,
} from "lucide-react";
import Container from "@/components/Container";
import ScrollReveal from "@/components/ScrollReveal";
import DashboardPlaceholder from "@/components/DashboardPlaceholder";
import SchemaMockup from "./SchemaMockup";

const NOISE_SVG = `url("data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.7' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)'/%3E%3C/svg%3E")`;

const methodBlocks = [
  { Icon: MapPinned, heading: "Hyper-local intent", desc: "Every page targets a specific city, neighborhood, and service combination. Content is written for how customers in that market actually search, not how the franchise headquarters thinks they search." },
  { Icon: Layers, heading: "Topical authority at scale", desc: "Each location builds topical depth across every service the franchise offers. Internal linking, content clusters, and schema relationships compound to establish authority Google rewards." },
  { Icon: Building2, heading: "Brand-aware optimization", desc: "Franchise brand standards constrain how content can be written. Soap's methodology optimizes within those constraints, never against them. Brand consistency and ranking, not a tradeoff." },
  { Icon: TrendingUp, heading: "Continuous refinement", desc: "Rankings change. Algorithms update. Competitors move. Soap monitors performance per page per location and adjusts content, structure, and signals on a continuous cycle." },
];

const auditFeatures = [
  "Technical audits: schema, structured data, page speed, mobile, accessibility",
  "Content audits: word count, keyword usage, internal links, freshness",
  "Competitor audits: ranking position, content gaps, backlink delta",
  "Citation audits: NAP consistency across directories",
  "Critical issues auto-resolved through the platform",
  "Strategic recommendations queued for review",
];

const schemaFeatures = [
  "LocalBusiness schema with full NAP and geo data",
  "Service schema per service offering",
  "FAQ schema on service pages",
  "Review schema pulling from GBP and platform reviews",
  "BreadcrumbList for navigation hierarchy",
  "Auto-validated against Google's schema requirements",
];

const contentCards = [
  { Icon: Sparkles, heading: "AI-drafted, human-reviewed", desc: "Drafts are generated by proprietary AI prompts trained on franchise marketing patterns. Every piece passes through human editorial review before it ships. Quality at scale." },
  { Icon: MapPin, heading: "Location-specific by default", desc: "Content is written for the city, neighborhood, and service intent of each page. Tampa storm damage content reads differently than Phoenix storm damage content. Local context is baked in." },
  { Icon: Repeat, heading: "Continuous publishing", desc: "Blogs, service page updates, area page refreshes, FAQ additions. Each location gets a continuous content schedule appropriate to its package tier. Freshness is a ranking signal." },
];

export function MethodologySection() {
  return (
    <section data-bg="light" className="relative px-6 py-[84px] md:px-16 md:py-[112px]" style={{ backgroundColor: "#F8FAFC" }}>
      <div className="pointer-events-none absolute inset-0" style={{ backgroundImage: NOISE_SVG, backgroundRepeat: "repeat", mixBlendMode: "soft-light", opacity: 0.1 }} />
      <Container className="relative">
        <ScrollReveal>
          <div className="text-center">
            <p className="text-[11px] font-bold uppercase tracking-[0.12em]" style={{ color: "#1570EF" }}>The Methodology</p>
            <h2 className="mx-auto mt-4 max-w-[760px] text-[34px] font-extrabold leading-tight tracking-[-0.02em] md:text-[46px]" style={{ color: "#0E172A" }}>
              Local SEO is not generic SEO.
            </h2>
            <p className="mx-auto mt-4 max-w-[720px] text-[16px] leading-[1.6] md:text-[17px]" style={{ color: "#1F1F1F" }}>
              Franchise SEO is different. Hundreds of pages, dozens of markets, brand standards to maintain, and competitors who all look the same to Google. Soap's methodology is built for this specific reality.
            </p>
          </div>
        </ScrollReveal>
        <div className="mt-14 grid grid-cols-1 gap-8 md:grid-cols-2">
          {methodBlocks.map((b, i) => (
            <ScrollReveal key={b.heading} delay={100 + i * 80} distance={20}>
              <b.Icon size={28} style={{ color: "#1570EF" }} />
              <h3 className="mt-4 text-[18px] font-bold" style={{ color: "#0E172A" }}>{b.heading}</h3>
              <p className="mt-3 text-[14px] leading-[1.6]" style={{ color: "#1F1F1F" }}>{b.desc}</p>
            </ScrollReveal>
          ))}
        </div>
      </Container>
    </section>
  );
}

export function AuditSection() {
  return (
    <section data-bg="white" className="px-6 py-[84px] md:px-16 md:py-[112px]">
      <Container>
        <div className="flex flex-col gap-10 md:flex-row md:items-center md:gap-16">
          <ScrollReveal className="md:w-[45%]">
            <p className="text-[11px] font-bold uppercase tracking-[0.12em]" style={{ color: "#1570EF" }}>Automated Audits</p>
            <h2 className="mt-4 text-[26px] font-bold leading-tight tracking-[-0.02em] md:text-[32px]" style={{ color: "#0E172A" }}>
              Every page audited. Every month.
            </h2>
            <p className="mt-4 text-[15px] leading-[1.6] md:text-[16px]" style={{ color: "#1F1F1F" }}>
              Soap runs comprehensive technical and content audits on every page across every location. Issues are flagged, prioritized, and routed to the right place. Critical issues get fixed automatically. Strategic issues get queued for the content team.
            </p>
            <ul className="mt-6 flex flex-col gap-3">
              {auditFeatures.map((f) => (
                <li key={f} className="flex items-start gap-2.5">
                  <Check size={16} style={{ color: "#1570EF", marginTop: 3, flexShrink: 0 }} />
                  <span className="text-[15px]" style={{ color: "#1F1F1F" }}>{f}</span>
                </li>
              ))}
            </ul>
          </ScrollReveal>
          <ScrollReveal delay={200} className="md:w-[55%]">
            <DashboardPlaceholder label="Audits" icon="image" />
          </ScrollReveal>
        </div>
      </Container>
    </section>
  );
}

export function SchemaSection() {
  return (
    <section data-bg="white" className="px-6 pb-[84px] md:px-16 md:pb-[112px]">
      <Container>
        <div className="flex flex-col gap-10 md:flex-row md:items-center md:gap-16">
          <ScrollReveal className="order-2 md:order-1 md:w-[55%]">
            <SchemaMockup />
          </ScrollReveal>
          <ScrollReveal delay={200} className="order-1 md:order-2 md:w-[45%]">
            <p className="text-[11px] font-bold uppercase tracking-[0.12em]" style={{ color: "#1570EF" }}>Schema Markup</p>
            <h2 className="mt-4 text-[26px] font-bold leading-tight tracking-[-0.02em] md:text-[32px]" style={{ color: "#0E172A" }}>
              The structured data Google needs to rank you.
            </h2>
            <p className="mt-4 text-[15px] leading-[1.6] md:text-[16px]" style={{ color: "#1F1F1F" }}>
              Soap deploys LocalBusiness, Service, FAQ, Review, and BreadcrumbList schema on every page automatically. Schema is validated continuously, updated when brand or location data changes, and structured for the rich results Google rewards.
            </p>
            <ul className="mt-6 flex flex-col gap-3">
              {schemaFeatures.map((f) => (
                <li key={f} className="flex items-start gap-2.5">
                  <Check size={16} style={{ color: "#1570EF", marginTop: 3, flexShrink: 0 }} />
                  <span className="text-[15px]" style={{ color: "#1F1F1F" }}>{f}</span>
                </li>
              ))}
            </ul>
          </ScrollReveal>
        </div>
      </Container>
    </section>
  );
}

export function ContentSection() {
  return (
    <section data-bg="light" className="relative px-6 py-[84px] md:px-16 md:py-[112px]" style={{ backgroundColor: "#F8FAFC" }}>
      <div className="pointer-events-none absolute inset-0" style={{ backgroundImage: NOISE_SVG, backgroundRepeat: "repeat", mixBlendMode: "soft-light", opacity: 0.1 }} />
      <Container className="relative">
        <ScrollReveal>
          <div className="text-center">
            <p className="text-[11px] font-bold uppercase tracking-[0.12em]" style={{ color: "#1570EF" }}>Content Engine</p>
            <h2 className="mx-auto mt-4 max-w-[720px] text-[34px] font-extrabold leading-tight tracking-[-0.02em] md:text-[46px]" style={{ color: "#0E172A" }}>
              Hyper-local content at portfolio scale.
            </h2>
            <p className="mx-auto mt-4 max-w-[680px] text-[16px] leading-[1.6] md:text-[17px]" style={{ color: "#1F1F1F" }}>
              Generic boilerplate does not rank. Soap's content engine produces location-specific, service-specific, brand-aligned content on a continuous schedule. AI-drafted, human-reviewed, performance-tracked.
            </p>
          </div>
        </ScrollReveal>
        <div className="mt-12 grid grid-cols-1 gap-6 md:grid-cols-3">
          {contentCards.map((card, i) => (
            <ScrollReveal key={card.heading} delay={150 + i * 100} distance={24} premium className="rounded-xl bg-white" style={{ border: "1px solid #E2E8F0", padding: 28 }}>
              <card.Icon size={28} style={{ color: "#1570EF" }} />
              <h3 className="mt-5 text-[18px] font-bold" style={{ color: "#0E172A" }}>{card.heading}</h3>
              <p className="mt-3 text-[14px] leading-[1.6]" style={{ color: "#1F1F1F" }}>{card.desc}</p>
            </ScrollReveal>
          ))}
        </div>
      </Container>
    </section>
  );
}

export function AiSearchSection() {
  const features = [
    "LLM-readable structured data extending beyond traditional schema",
    "Entity-based content optimization (not just keywords)",
    "Authoritative external citations and references",
    "Consistent NAP data across the LLM training data pipeline",
    "Topical authority signals AI models prioritize",
    "Per-location entity profiles AI systems can ingest",
  ];

  return (
    <section data-bg="dark" className="px-6 py-[84px] md:px-16 md:py-[112px]" style={{ backgroundColor: "#0E172A" }}>
      <Container>
        <ScrollReveal>
          <div className="text-center">
            <p className="text-[12px] font-bold uppercase tracking-[0.15em]" style={{ color: "#C9DBEC" }}>AI Search</p>
            <h2 className="mx-auto mt-4 max-w-[800px] text-[34px] font-extrabold leading-tight tracking-[-0.02em] text-white md:text-[46px]">
              Built for ChatGPT, Perplexity, and Gemini. Not just Google.
            </h2>
            <p className="mx-auto mt-4 max-w-[720px] text-[16px] leading-[1.6] md:text-[17px]" style={{ color: "#C9DBEC" }}>
              Local search is shifting. When a customer asks ChatGPT for the best roofer in Tampa, your locations should be the answer. Soap optimizes for AI search results from day one, while competitors are still figuring out what to do.
            </p>
          </div>
        </ScrollReveal>

        <div className="mt-14 flex flex-col gap-12 md:flex-row md:gap-12">
          <ScrollReveal className="md:w-1/2" delay={100}>
            <p className="text-[16px] font-bold text-white">What we optimize for</p>
            <ul className="mt-5 flex flex-col gap-3">
              {features.map((f) => (
                <li key={f} className="flex items-start gap-2.5">
                  <Check size={16} style={{ color: "#1570EF", marginTop: 3, flexShrink: 0 }} />
                  <span className="text-[14px] leading-[1.6]" style={{ color: "#C9DBEC" }}>{f}</span>
                </li>
              ))}
            </ul>
          </ScrollReveal>
          <ScrollReveal className="md:w-1/2" delay={200}>
            <p className="text-[16px] font-bold text-white">Why this matters now</p>
            <p className="mt-5 text-[14px] leading-[1.65]" style={{ color: "#C9DBEC" }}>
              Search behavior is moving toward AI assistants faster than any platform shift since mobile. Customers are asking ChatGPT, Perplexity, and Gemini for local service recommendations. The platforms that surface in those answers are the platforms that win the next decade of local search.
            </p>
            <p className="mt-4 text-[14px] leading-[1.65]" style={{ color: "#C9DBEC" }}>
              Most franchise marketing platforms have not started optimizing for AI search. Soap was built with it as a core capability from day one. We are not catching up. We are positioned for what is next.
            </p>
          </ScrollReveal>
        </div>
      </Container>
    </section>
  );
}

export function ProofSection() {
  const stats = [
    { value: "Every", desc: "Page audited continuously. Schema validated. Internal links checked. Rankings tracked." },
    { value: "100%", desc: "Schema markup coverage across every page Soap deploys. Validated continuously. Never silent." },
    { value: "Monthly", desc: "Comprehensive performance audits per location, with continuous automated monitoring in between." },
  ];

  return (
    <section data-bg="white" className="px-6 py-[84px] md:px-16 md:py-[112px]">
      <Container>
        <ScrollReveal>
          <div className="text-center">
            <p className="text-[11px] font-bold uppercase tracking-[0.12em]" style={{ color: "#1570EF" }}>Proof</p>
            <h2 className="mx-auto mt-4 max-w-[720px] text-[34px] font-extrabold leading-tight tracking-[-0.02em] md:text-[46px]" style={{ color: "#0E172A" }}>
              Built by operators who have done this work.
            </h2>
            <p className="mx-auto mt-4 max-w-[680px] text-[16px] leading-[1.6] md:text-[17px]" style={{ color: "#1F1F1F" }}>
              Soap's SEO methodology comes from years of agency work, refined into a platform. Not theory. Not best practices recycled from blog posts. Methodology that has actually moved rankings at the location level.
            </p>
          </div>
        </ScrollReveal>
        <div className="mt-12 grid grid-cols-1 gap-6 md:grid-cols-3">
          {stats.map((s, i) => (
            <ScrollReveal key={s.value} delay={150 + i * 100} distance={24} premium className="rounded-xl bg-white" style={{ border: "1px solid #E2E8F0", padding: 28 }}>
              <p className="text-[44px] font-extrabold" style={{ color: "#1570EF" }}>{s.value}</p>
              <p className="mt-3 text-[14px] leading-[1.5]" style={{ color: "#1F1F1F" }}>{s.desc}</p>
            </ScrollReveal>
          ))}
        </div>
        <ScrollReveal delay={500}>
          <p className="mt-8 text-center text-[13px] italic" style={{ color: "#71717A" }}>
            Real customer case studies will be added as Soap deploys across enterprise portfolios. Until then, what you see in a demo is what you get.
          </p>
        </ScrollReveal>
      </Container>
    </section>
  );
}

export function IntegrationSection() {
  const cards = [
    { eyebrow: "LOCATIONS", heading: "SEO architecture is built into every page", desc: "Every service page, every area page, every location section ships with schema, internal links, and on-page optimization. SEO is not a layer applied later. It is the foundation.", href: "/locations" },
    { eyebrow: "GOOGLE BUSINESS PROFILE", heading: "GBP signals reinforce on-page rankings", desc: "GBP performance, post velocity, review signals, and photo updates feed the local pack rankings that complement on-page SEO. Both work together.", href: "/google-business-profile" },
    { eyebrow: "PLATFORM", heading: "Visibility for franchisors and franchisees", desc: "Corporate sees SEO performance across the portfolio. Franchisees see their own location's rankings and traffic. Everyone operates from the same data.", href: "/platform" },
  ];

  return (
    <section data-bg="light" className="relative px-6 py-[84px] md:px-16 md:py-[112px]" style={{ backgroundColor: "#F8FAFC" }}>
      <div className="pointer-events-none absolute inset-0" style={{ backgroundImage: NOISE_SVG, backgroundRepeat: "repeat", mixBlendMode: "soft-light", opacity: 0.1 }} />
      <Container className="relative">
        <ScrollReveal>
          <div className="text-center">
            <p className="text-[11px] font-bold uppercase tracking-[0.12em]" style={{ color: "#1570EF" }}>Integrated</p>
            <h2 className="mx-auto mt-4 max-w-[800px] text-[34px] font-extrabold leading-tight tracking-[-0.02em] md:text-[46px]" style={{ color: "#0E172A" }}>
              SEO is not a feature. It is the foundation.
            </h2>
            <p className="mx-auto mt-4 max-w-[720px] text-[16px] leading-[1.6] md:text-[17px]" style={{ color: "#1F1F1F" }}>
              Every part of Soap reinforces every other part. Locations get pages, pages get optimized, GBPs get managed, reviews get gathered, content gets produced. SEO is the through-line connecting all of it.
            </p>
          </div>
        </ScrollReveal>
        <div className="mt-12 grid grid-cols-1 gap-6 md:grid-cols-3">
          {cards.map((card, i) => (
            <ScrollReveal key={card.eyebrow} delay={150 + i * 100} distance={24} premium className="flex flex-col rounded-xl bg-white" style={{ border: "1px solid #E2E8F0", padding: 24 }}>
              <p className="text-[11px] font-bold uppercase tracking-[0.08em]" style={{ color: "#0E172A" }}>{card.eyebrow}</p>
              <h3 className="mt-2 text-[16px] font-bold" style={{ color: "#0E172A" }}>{card.heading}</h3>
              <p className="mt-3 flex-1 text-[13px] leading-[1.55]" style={{ color: "#1F1F1F" }}>{card.desc}</p>
              <Link href={card.href} className="arrow-link mt-4 inline-flex items-center gap-1 text-[13px] font-semibold" style={{ color: "#1570EF" }}>
                Learn more <span className="arrow-icon">&rarr;</span>
              </Link>
            </ScrollReveal>
          ))}
        </div>
      </Container>
    </section>
  );
}
